basketball:
    region:
        world: "world"
        loc1:
            x: -32
            y: 56
            z: 85
        loc2:
            x: 14
            y: 56
            z: 109
        y: 55
    hoop1:
        world: "world"
        loc1:
            x: -32
            y: 65
            z: 96
        loc2:
            x: -31
            y: 65
            z: 98
        y: 65
    hoop2:
        world: "world"
        loc1:
            x: 13
            y: 65
            z: 96
        loc2:
            x: 14
            y: 65
            z: 98
        y: 65
koth:
    region:
        world: "world"
        loc1:
            x: -77
            y: 64
            z: 44
        loc2:
            x: -73
            y: 64
            z: 48
        y: 64